micronaut:
  http:
    client:
      event-loop-group: custom-event-loop
  netty:
    event-loops:
      custom-event-loop:
        num-threads: 20
    default:
      allocator:
        max-order: 3
  server:
    thread-selection: auto
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins:
            - http://localhost:3000/*
            - chrome-extension://clnolpcnobmkanpcjkgmaoamigkbinhf
            - http://adf474755d5054540877b7fc5e73dcd8-1535721202.us-east-2.elb.amazonaws.com:3000/*
            - http://10.100.144.148:3000/*
            - "*"
    port: ${SERVER_PORT:8081}
    max-request-size: 1GB
    multipart:
      max-file-size: 100MB
      mixed: true
      disk: true
  application:
    name: demo
  security:
    authentication: bearer
    endpoints:
      login:
        enabled: true
    redirect:
      enabled: false
    token:
      jwm:
        enabled: true
        signatures:
          jwks:
            keycloak:
                url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/${KEYCLOAK_REALM:keycloak-react-auth}/protocol/openid-connect/certs
    oauth2.clients.keycloak:
      keycloak-port: ${KEYCLOAK_PORT:8080}
      keycloak-host: ${KEYCLOAK_HOST:localhost}
      realm-name: ${KEYCLOAK_REALM:keycloak-react-auth}
      grant-type: password
      client-id: ${KEYCLOAK_CLIENT:react-client}
      client-secret: ${KEYCLOAK_SECRET}
      authorization:
        url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/${KEYCLOAK_REALM:keycloak-react-auth}/protocol/openid-connect/auth
      token:
        url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/${KEYCLOAK_REALM:keycloak-react-auth}/protocol/openid-connect/token
        auth-method: client-secret-post
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgrespwd}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:varxen-db}
jpa.default.properties.hibernate.hbm2ddl.auto: update
performance-frameworks:
  locust:
    host: ${LOCUST_HOST:c782-2800-484-d37f-3f3-6a59-4b01-5ca2-b018.ngrok-free.app}
    port: ${LOCUST_PORT:80}
azure:
  storage:
    container:
      name: ${AZURE_CONTAINER_NAME}
    connection:
      string: ${AZURE_CONNECTION_STRING}