micronaut:
  server:
    cors:
      enabled: true
    port: ${SERVER_PORT:8080}
  application:
    name: demo
  security:
    authentication: idtoken
    endpoints:
      login:
        enabled: true
    redirect:
      enabled: false
    token:
      jwm:
        enabled: true
        signatures:
          jwks:
            keycloak:
              url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8081}/realms/${KEYCLOAK_REALM:keycloak-react-auth}/protocol/openid-connect/certs
    oauth2.clients.keycloak:
      keycloak-port: ${KEYCLOAK_PORT:8081}
      keycloak-host: ${KEYCLOAK_HOST:localhost}
      realm-name: ${KEYCLOAK_REALM:keycloak-react-auth}
      grant-type: password
      client-id: ${KEYCLOAK_CLIENT:react-client}
      client-secret: ${KEYCLOAK_SECRET:So1GhoZqaboA20JsGud6zKp5hCyqEj0y}
      authorization:
        url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8081}/realms/${KEYCLOAK_REALM:keycloak-react-auth}/protocol/openid-connect/auth
      token:
        url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8081}/realms/${KEYCLOAK_REALM:keycloak-react-auth}/protocol/openid-connect/token
        auth-method: client-secret-post
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:varxen-db}
netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: update
