micronaut:
  server:
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins:
            - http://localhost:3000
            - http://localhost:3000/VarxenPerformance/Session
            - chrome-extension://clnolpcnobmkanpcjkgmaoamigkbinhf
    port: ${SERVER_PORT:8081}
    max-request-size: 1GB
    multipart:
      max-file-size: 100MB
      mixed: true
      disk: true
  application:
    name: demo
  security:
    authentication: bearer
    endpoints:
      login:
        enabled: true
    redirect:
      enabled: false
    token:
      jwm:
        enabled: true
        signatures:
          jwks:
            keycloak:
                url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/${KEYCLOAK_REALM:keycloak-react-auth}/protocol/openid-connect/certs
    oauth2.clients.keycloak:
      keycloak-port: ${KEYCLOAK_PORT:8080}
      keycloak-host: ${KEYCLOAK_HOST:localhost}
      realm-name: ${KEYCLOAK_REALM:keycloak-react-auth}
      grant-type: password
      client-id: ${KEYCLOAK_CLIENT:react-client}
      client-secret: ${KEYCLOAK_SECRET}
      authorization:
        url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/${KEYCLOAK_REALM:keycloak-react-auth}/protocol/openid-connect/auth
      token:
        url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/${KEYCLOAK_REALM:keycloak-react-auth}/protocol/openid-connect/token
        auth-method: client-secret-post
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgrespwd}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:varxen-db}
netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: update
azure:
  storage:
    container:
      name: ${AZURE_CONTAINER_NAME}
    connection:
      string: ${AZURE_CONNECTION_STRING}