micronaut:
  application:
    name: demo
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/varxen-db
netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: update
