micronaut:
  server:
    port: 8081
  application:
    name: demo
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    url: jdbc:postgresql://localhost:49153/varxen-db
    username: postgres
    password: postgrespw
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
    entity-scan:
      packages:
        'edu.co.icesi.model'
azure:
  storage:
    container:
      name: ${AZURE_CONTAINER_NAME}
    connection:
      string: ${AZURE_CONNECTION_STRING}