micronaut:
  application:
    name: demo
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    url: ${POSTGRES_CONNECTION_STRING:jdbc:postgresql://localhost:5432/varxen-db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgrespwd}
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
azure:
  storage:
    container:
      name: ${AZURE_CONTAINER_NAME}
    connection:
      string: ${AZURE_CONNECTION_STRING}